# PUSHD {PATH}
# docker build -f %CD%\Dockerfile_awsBrew -t awsbrew:test .
# docker rmi awsbrew:test

# file : .\Dockerfile.aws

# $ docker images awsbrew:test & REM base のみ
# REPOSITORY   TAG       IMAGE ID       CREATED         SIZE
# awsbrew      test      905377223a40   9 minutes ago   1.14GB


# -- ------------------------------------------------------------------------------------------------------------
# ベースイメージを指定
# -- ------------------------------------------------------------------------------------------------------------
FROM amazonlinux:latest


# -- ------------------------------------------------------------------------------------------------------------
RUN yum groupinstall -y 'Development Tools' && yum install -y curl file git curl-devel
RUN yum -y install gcc make autoconf sudo diffutils vi wget tar which

RUN adduser brew
RUN echo 'brew:hoge' |chpasswd
RUN usermod -G wheel brew

# Step By Step

# https://qiita.com/beeeyan/items/ef72532701bb8219bc55
# google : dockerhub brew


