# 
# Lamp系（LNMP）/ Docker-alpine 
# https://qiita.com/masakielastic/items/e08240583215884d41a2  
#  
#  
# PHP8 
# https://externals.io/message/112026#112251 
#  
# https://wiki.php.net/todo/php80  
#  
# https://phpcon.connpass.com  
# https://phpcon.connpass.com/event/193141/ 
# 
# https://externals.io/message/112258  
# 
