- 5分で学ぶ: カオスエンジニアリングの説明書		
    - https://blog.newrelic.co.jp/engineering/chaos-engineering-explained/
    - memo : ChaosTest ... TestingFramework

    - → Netflex が発祥らしい	
        - google : chaos engineering	

        - 他
            - カオスエンジニアリングと聞いてカオスになった人必見 - Qiita
                - https://qiita.com/naokiiiii/items/de20997a70922c01f754