# google ; redhat ansible
# google : docker ansible
# google : docker ansible windows

# https://qiita.com/myalpine/items/ea18b3b22c14c60efc3c
# https://qiita.com/Tkm08/items/58e1fb7990387a2e9c76

# [RedHat公式]

# google : ひよこ大佐 ansible slideshare

# https://www.slideshare.net/ShingoKitayama/red-hat-forum-2017-ansible-towerinfrastructure-as-code


# https://github.com/ansible/ansible
# https://www.redhat.com/ja/technologies/management/ansible
# https://www.ansible.com/resources/get-started
# https://www.redhat.com/ja/explore/ansible
# https://www.redhat.com/ja/explore/ansible#topics
# https://www.redhat.com/ja/engage/ansible-automation-platform-s-202004051827
# 
