Docker で tags付け
https://books.google.co.jp/books?id=U-WoDwAAQBAJ&pg=PA93&lpg=PA93&dq=perl+alpine&source=bl&ots=LJkT-6GkA6&sig=ACfU3U34V0ZMWM0sv0trG4FhIal1JV818A&hl=ja&sa=X&ved=2ahUKEwj027SdwMbtAhWZfd4KHYEDB0E4ChDoATAJegQIBRAC#v=onepage&q=perl%20alpine&f=false

