# https://kubernetes.io/ja/docs/tutorials/hello-minikube/

# https://kubernetes.io/ja/docs/tutorials/stateless-application/guestbook/


# Google : Katakoda
# https://www.katacoda.com/

# GOOGLE : kubectl チュートリアル　ブラウザ
# https://qiita.com/loftkun/items/7804f19c4a34f56744f6

# https://cstoku.dev/posts/2018/k8sdojo-23/