# google : docker php vscode
# google : docker php vscode browser版


# https://qiita.com/h-r-k-matsumoto/items/01defc9748eca1565bcf


# Docker上のPHPをxdebugでVisualStudioCodeからデバッグする設定
# https://qiita.com/hiro-tarosuke/items/adcc382ca98dfb89401b

# VS CodeでDockerのPHP環境でリモート開発
# https://qiita.com/chigusaweb66/items/6737f812549cb299dc52

# Docker × Visual Studio CodeでPHP開発【デバッグ実行】
# https://qiita.com/MasanoriIwakura/items/a310c75e6c5b347adf37

