
# mongo-express
# https://hub.docker.com/_/mongo-express
# -- --------------
# https://github.com/Dereje1/Pinterest-Clone
# -- --------------
# -- 
# # docker run --rm --network some-network -e ME_CONFIG_MONGODB_SERVER=some-mongo -p 8081:8081 mongo-express
# docker run --rm -e ME_CONFIG_MONGODB_SERVER=some-mongo -p 8081:8081 mongo-express # これでもだめ？

