# 今Movable Type再入門するためにDocker環境を整備した作業ログ - Qiita # docker-composeymlを更新してmovable-typeが動作する所まで持って行く
# https://qiita.com/uehatsu/items/55504c8804bbede3a6bb#docker-composeyml%E3%82%92%E6%9B%B4%E6%96%B0%E3%81%97%E3%81%A6movable-type%E3%81%8C%E5%8B%95%E4%BD%9C%E3%81%99%E3%82%8B%E6%89%80%E3%81%BE%E3%81%A7%E6%8C%81%E3%81%A3%E3%81%A6%E8%A1%8C%E3%81%8F
# https://hub.docker.com/r/mailhog/mailhog/dockerfile

#
# MailHog Dockerfile
#

FROM alpine:3.4

# Install ca-certificates, required for the "release message" feature:
RUN apk --no-cache add \
    ca-certificates

# Install MailHog:
RUN apk --no-cache add --virtual build-dependencies \
    go \
    git \
  && mkdir -p /root/gocode \
  && export GOPATH=/root/gocode \
  && go get github.com/mailhog/MailHog \
  && mv /root/gocode/bin/MailHog /usr/local/bin \
  && rm -rf /root/gocode \
  && apk del --purge build-dependencies

# Add mailhog user/group with uid/gid 1000.
# This is a workaround for boot2docker issue #581, see
# https://github.com/boot2docker/boot2docker/issues/581
RUN adduser -D -u 1000 mailhog

USER mailhog

WORKDIR /home/mailhog

ENTRYPOINT ["MailHog"]

# Expose the SMTP and HTTP ports:
EXPOSE 1025 8025

#
# MailHog Dockerfile
#

FROM alpine:3.4

# Install ca-certificates, required for the "release message" feature:
RUN apk --no-cache add \
    ca-certificates

# Install MailHog:
RUN apk --no-cache add --virtual build-dependencies \
    go \
    git \
  && mkdir -p /root/gocode \
  && export GOPATH=/root/gocode \
  && go get github.com/mailhog/MailHog \
  && mv /root/gocode/bin/MailHog /usr/local/bin \
  && rm -rf /root/gocode \
  && apk del --purge build-dependencies

# Add mailhog user/group with uid/gid 1000.
# This is a workaround for boot2docker issue #581, see
# https://github.com/boot2docker/boot2docker/issues/581
RUN adduser -D -u 1000 mailhog

USER mailhog

WORKDIR /home/mailhog

ENTRYPOINT ["MailHog"]

# Expose the SMTP and HTTP ports:
EXPOSE 1025 8025

# docker build -f %AppData%\Docker\Dockerfiles\Dockerfile_mailhog -t mailhog_test .
# docker build -f %AppData%\Docker\Dockerfiles\Dockerfile_mailhog -t tmsa34106/mailhog_test .

#   DIR %AppData%\Docker\Dockerfiles\Dockerfile_mailhog


# docker images mailhog_test
# # REPOSITORY          TAG                 IMAGE ID            CREATED              SIZE
# # mailhog_test        latest              a179ba0c53a3        About a minute ago   19.1MB

# docker images | head -1 & docker images | grep mailhog_test
# # # docker images | head -1 | CLIP & docker images | grep mailhog_test | CLIP
# # REPOSITORY                           TAG                                              IMAGE ID            CREATED             SIZE
# # tmsa34106/mailhog_test               latest                                           a179ba0c53a3        3 minutes ago       19.1MB
# # mailhog_test                         latest                                           a179ba0c53a3        3 minutes ago       19.1MB


# docker push tmsa34106/mailhog_test
# # https://hub.docker.com/repository/docker/tmsa34106/mailhog_test
# docker pull tmsa34106/mailhog_test




