

# Docker Blog
# 

# DockerWSL2がGPUサポート / WSL 2 GPU Support is Here
# https://www.docker.com/blog/wsl-2-gpu-support-is-here/ 

  # 一次ソースはここだった
  # Docker Desktop for Windows Homeには何が含まれていますか？/ Docker Desktop for Windows Home is here! 
  # 2020年3月5日　←ここがすべての情報源だ！ 
  # https://www.docker.com/blog/docker-desktop-for-windows-home-is-here/ 

# Download and Try the Tech Preview of Docker Desktop for M1
# https://www.docker.com/blog/download-and-try-the-tech-preview-of-docker-desktop-for-m1/
# Docker In ARM

# Docker Desktop 3.0.0: Smaller, Faster Releases
# https://www.docker.com/blog/docker-desktop-3-0-0-smaller-faster-releases/
# →2.xからup、大変良い感じ

# The Docker Developer Guide to AWS re:Invent
# https://www.docker.com/blog/the-docker-developer-guide-to-aws-reinvent/
# MATT CARTER ... LinkedIn


# The Docker Developer Guide to AWS re:Invent
# https://www.docker.com/blog/the-docker-developer-guide-to-aws-reinvent/
# # Werner Vogels Keynote
# # . TUESDAY, DEC. 15, 8:00 AM – 9:30 AM (PST)
# # . Join Dr. Werner Vogels as he goes behind the scenes to show how Amazon is solving today’s hardest technology problems. Based on his experience working with some of the largest and most successful applications in the world, Dr. Vogels shares his insights on building truly resilient architectures and what that means for the future of software development.
# # まさかの指導教官が、タンネンバウム大先生

# そのほか取りまとめ中 
# https://www.docker.com/blog/docker-hub-experimental-cli-tool/ 
# https://www.docker.com/blog/connecting-with-the-docker-community-recap-of-our-first-community-all-hands/ 
# https://www.docker.com/blog/secure-from-the-start-shift-vulnerability-scanning-left-in-docker-desktop/  
# https://www.docker.com/blog/the-docker-developer-guide-to-aws-reinvent/  
# https://www.docker.com/blog/docker-compose-for-amazon-ecs-now-available/  



# 沼話題

# オーケストレーション（）

# https://www.itmedia.co.jp/enterprise/articles/2010/23/news009.html

# もう一度生まれ変わっても、あなたは情シスの仕事をしますか？【情シス意識調査】
# テレワーク対応で多忙な中、予算は増えず、人も増えない。「八方ふさがり」「四面楚歌」――。
# そんなネガティブな言葉が浮かぶ状況かと思いきや、調査によると予想外の希望の光が見えてきました。調査結果から情シスの未来を占ってみましょう。


# Qitta Advent
# https://qiita.com/advent-calendar/2020
# https://qiita.com/advent-calendar

